# Generated by Django 4.0.6 on 2022-07-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('SerialNumber', models.AutoField(primary_key=True, serialize=False)),
                ('Slug', models.CharField(max_length=50)),
                ('SongTitle', models.CharField(max_length=50)),
                ('SongArtist', models.CharField(max_length=50)),
                ('SongDuration', models.CharField(max_length=6)),
                ('SongAudio', models.FileField(blank=True, null=True, upload_to='')),
                ('SongCover', models.FileField(blank=True, null=True, upload_to='')),
                ('SongVideo', models.FileField(blank=True, null=True, upload_to='')),
                ('SongDescription', models.TextField()),
            ],
        ),
    ]
