# Generated by Django 4.0.6 on 2022-08-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicWebApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('EmailID', models.EmailField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('EmailID', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='SongAudio',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='SongDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
