# Generated by Django 4.0.6 on 2022-08-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicWebApplication', '0003_alter_contact_phonenumber_alter_song_songaudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='SongAlbum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='SongFeaturedArtist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='SongReleased',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
