# Generated by Django 4.0.6 on 2022-08-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicWebApplication', '0004_song_songalbum_song_songfeaturedartist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='EmailID',
            new_name='Email_ID',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='PhoneNumber',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SerialNumber',
            new_name='Serial_Number',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongAlbum',
            new_name='Song_Album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongArtist',
            new_name='Song_Artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongAudio',
            new_name='Song_Audio',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongCover',
            new_name='Song_Cover',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongDescription',
            new_name='Song_Description',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongDuration',
            new_name='Song_Duration',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongFeaturedArtist',
            new_name='Song_Featured_Artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongReleased',
            new_name='Song_Released',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongTitle',
            new_name='Song_Title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='SongVideo',
            new_name='Song_Video',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='EmailID',
            new_name='Email_ID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.AddField(
            model_name='song',
            name='Song_Lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
