# Generated by Django 4.0.6 on 2022-08-17 10:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicWebApplication', '0005_rename_emailid_contact_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Song_Cover_File_Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_Cover',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='Media/SongCovers'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_Description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
