# Generated by Django 4.0.6 on 2022-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicWebApplication', '0006_song_song_cover_file_name_alter_song_song_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Song_Audio_File_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='Song_Video_File_Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_Cover_File_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
