# Generated by Django 4.0.6 on 2022-08-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicWebApplication', '0008_alter_song_song_audio_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Song_Audio_File_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
