# Generated by Django 4.0.6 on 2022-08-23 07:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicWebApplication', '0009_alter_song_song_audio_file_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_Audio',
            field=models.FileField(default=0, storage=django.core.files.storage.FileSystemStorage(location='Media/SongAudios'), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_Audio_File_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_Cover',
            field=models.ImageField(default=0, storage=django.core.files.storage.FileSystemStorage(location='Media/SongCovers'), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_Video',
            field=models.FileField(blank=True, default=0, storage=django.core.files.storage.FileSystemStorage(location='Media/SongVideos'), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='Song_Video_File_Name',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
